### ISSUE TITLE
Use package:collection for collection comparison

### ISSUE THREAD

**Issue by polux** [dikmax/md_proc#1]
Hi,

I was curious about what you're using package:parsers for and found this project (nice project!). I remarked that you implemented maps and iterable comparison functions, which are available in this (google-maintained) package already: http://pub.dartlang.org/packages/collection.

Also if you're porting Haskell code you might be interested in some of my other projects: [persistent](http://pub.dartlang.org/packages/persistent) efficient immutable lists, maps and sets, [propcheck](http://pub.dartlang.org/packages/propcheck) a quickcheck/smallcheck test library which uses a port of testing-feat for generating enumerations, [adts](http://polux.github.io/adts/main.html) for generating Dart classes from algebraic datatype declarations, and [pretty](https://github.com/polux/pretty) a port of wl-pprint.

**Comment by dikmax** [comment]
Oh, didn't know about collection package. Thank you.
And I definitely check other libraries, especially adts and pretty.
