### ISSUE TITLE
don't process math blocks

### ISSUE THREAD

**Issue by kasperpeulen** [dikmax/md_proc#12]
Would it be possible to have an extension that doesn't process math blocks (that could be rendered by mathjax afterwards) ?

**Comment by dikmax** [comment]
Could you please add some example?

**Comment by kasperpeulen** [comment]
@dikmax 
There are a couple of places where LaTeX math blocks and markdown are conflicting. I think the best would be to have an extension that doesn't process anything between:

``` TeX
$ 1+1 = 2 $
```

``` TeX
$$ 1+1 = 2 $$
```

``` TeX
\( 1+1 = 2 \)
```

``` TeX
\[ 1+1 = 2 \]
```

So then mathjax could parse those math block after markdown has been parsed.

This is an example where things go wrong:
![image](https://cloud.githubusercontent.com/assets/1035299/11955722/9752d59c-a8b4-11e5-90e9-9f72df0c3efe.png)

Also braces are eaten up:
![image](https://cloud.githubusercontent.com/assets/1035299/11955785/158d2c50-a8b5-11e5-94ce-e93310e71bad.png)

See http://kasperpeulen.github.io/mathedit/ if you want to try yourself.

**Comment by dikmax** [comment]
I'll surely make math extension at least with $ and $$ as delimiters. I'll take pandoc description, but I'm not sure about `\[` and `\(`, because it breaks links escaping.

**Comment by kasperpeulen** [comment]
@dikmax that would be great.

Would like to have also `\[` and `\(` but I see that this really breaks markdown normal behaviour (although maybe in practice people rarely escape links).

**Comment by dikmax** [comment]
Fixed in 0.7.4.
Both syntaxes are supported by enabling different extensions. Look [README](https://github.com/dikmax/md_proc/blob/master/README.md) for more details.

**Comment by kasperpeulen** [comment]
@dikmax awesome, thank you!
