### ISSUE TITLE
possibiliy to define an extension ?

### ISSUE THREAD

**Issue by kasperpeulen** [dikmax/md_proc#2]
This seems like a very nice markdown parser. Is it possible to define some extension ? I have some troubles parsing documentation from dart (`dartdoc`) with this parser, as dartdoc uses some non-standard markdown. For example the `[myArg]` notation.

But anyway, seems like excellent work ! :+1:

**Comment by dikmax** [comment]
Unfortunately, extensions (user defined parsing code) not allowed yet. I'm not sure if they will be allowed in future. 
If you mean some more or less standard one (footnotes, math, etc.), i will eventually implement them. But it's not a priority right not.
Of course, any help is welcome.

**Comment by dikmax** [comment]
@kasperpeulen BTW, what do you mean by `[myArg]` notation?

**Comment by kasperpeulen** [comment]
Well a doc may look like this:

```
  /**
   * Programatically set the size of the editor (overriding the applicable CSS
   * rules). [width] and [height] can be either numbers (interpreted as pixels)
   * or CSS units ("100%", for example). You can pass `null` for either of them
   * to indicate that that dimension should not be changed.
   */
  void setSize(width, height)
```

So now commonmark won't do anything with `[width]` or `[height]`. I think it would be nice if I could define an extension that says, treat anything between `[...]` (and not followed by `(...)`) just as regular code. Or treat it like regular code, and make it link to `https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/$library/$ClassName:$link` or whatever...

**Comment by dikmax** [comment]
I see.
Actually, you don't need special extension to make this work. `[width]` and `[height]` are just links in terms of CommonMark. All you need is custom reference resolver, which will return proper link based on reference name.
I'll try to find time to implement support for custom resolvers this weekend.

**Comment by dikmax** [comment]
I've made it bit earlier. You can find usage example in README.
New package is uploaded to pub too.

**Comment by kasperpeulen** [comment]
Ah you are awesome! :+1: thanks :)
