### ISSUE TITLE
Note on UTF-8 and smart punctation

### ISSUE THREAD

**Issue by Scorpiion** [dikmax/md_proc#8]
Hi Maxim and thanks for implementing this package, it seem very nice.

I started using it now and ran into some issues with "Smart punctuation" and Dart's default encoding (Latin 1). It was a hard to find the issue because you only get a somewhat random error but after some debugging I realized that Latin 1 is the default encoding (for Dart:io HttpClientRequest) and it simply does not have "smart quotes", see comment 4 here: http://stackoverflow.com/a/9282615

What I had to do to get things working was to explicitly set the charset like this on the headers:

``` dart
res.headers.contentType = new ContentType("text", "html", charset: "utf-8");
```

Now it works without errors and I can render commonmark with md_proc server side and then send the output directly to a client.

This is not a bug per say in md_proc, but I think this might be common enough that it's worth documenting somewhere. Not sure exactly where, but maybe some small note in the readme on smart punctuation that if you plan to write that output to a HttpClientRequest you need to set the encoding explicitly to utf-8 or some other charset that supports smart quotes.

Cheers, Robert

**Comment by dikmax** [comment]
Somewhere in CommonMark specification is written that only supported encoding is UTF-8. I think I can copy this passage to readme.

**Comment by Scorpiion** [comment]
Okay, I have not read the whole spec.. But that sounds like a good idea. :+1:

**Comment by Scorpiion** [comment]
Dart's default encoding is described here at the top of this documentation page:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:io.HttpClientRequest

**Comment by dikmax** [comment]
Fixed.

**Comment by Scorpiion** [comment]
:+1:
